padding-x = 10
padding-y = [10, 10]
confirm-before-quit = false

[window]
width = 600
height = 400
mode = "maximized"
opacity = 0.8
blur = false
decorations = "enabled"
colorspace = "display-p3"

[navigation]
mode = "TopTab"
clickable = true
hide-if-single = false
use-current-path = false
color-automation = []

[shell]
program = "nu"
args = []

