tab_bar_edge top
tab_bar_style powerline
font_size 12
hide_window_decorations yes
shell fish

# BEGIN_KITTY_FONTS
font_family      family='Fira Code' features=+calt
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
